### ISSUE TITLE
Infaillible Epoch::now() ?

### ISSUE THREAD

**Issue by gwbres** [nyx-space/hifitime#177]
Hello Chris,

can't we just come up with something smart here, maybe in a seperate `infaillible` method, for use cases where we want an (ideally reasonnable) fallback value and do not allow the program to crash ?

https://github.com/nyx-space/hifitime/blob/2fdd90ab597296d311ec0a0c2690f4b0d4607d8e/src/epoch.rs#L2394

**Comment by ChristopherRabotin** [comment]
Hi Guillaume,

The issue is that the std system time call may fail. And this is what we
catch to return a hifitime error. One option on the user end is to call the
ok_or_else() function on the result to provide an alternative if the call
failed.

For example : Epoch::system_now().ok_or_else(||
Epoch::from_tai_seconds(0)).unwrap(). I think that should work, or
something similar.

Would that fit your use case?

**Comment by gwbres** [comment]
>Would that fit your use case?

Yes that would work, and it's actually better to deal with it on the user end
thanks

**Comment by ChristopherRabotin** [comment]
Great!

For future reference, here is the link to the docs
https://doc.rust-lang.org/std/result/enum.Result.html#method.or_else
