### ISSUE TITLE
`from_time_of_week` is not the reciprocate of `to_time_of_week` when the reference epoch is J1900

### ISSUE THREAD

**Issue by ChristopherRabotin** [nyx-space/hifitime#187]
The following fails, and I just do not understand why:

```rust
let epoch_utc = epoch.in_time_scale(TimeScale::UTC);
println!("{epoch:?}\t{epoch_utc:?}");
let (utc_wk, utc_tow) = epoch_utc.to_time_of_week();
assert_eq!(Epoch::from_time_of_week_utc(utc_wk, utc_tow), epoch_utc);
```

There is an offset of one day.

My hunch is that something is wrong with `to_time_of_week` but I don't understand why or where.

This happens for UTC, TT, and TAI. For ET and TDB, there is a small offset, most likely due to these time scales using an iteration for initialization (but that is not an "exactly one day" time error).

Note: this is currently hot fixed in the code of `from_time_of_week`.

**Comment by gwbres** [comment]
I identified the problem but I have not found a way to solve it

The problem is specific to the new methods 

- `to_time_of_week` 
- `from_time_of_week` 

the week counter specificly. 

In these methods, we're trying to build an epoch, in a time scale, from a week counter.
And we do not consider a possible day offset, due to the time scale weekday starting point.

Take TAI/UTC that started on a Monday. 
I'm pretty sure TAI <=> UTC operations work perfectly fine.

Apparently, all GNSS timescales started on a Sunday. 
Take a GPST <=> UTC operations, we get the +/-1 day offset.
The sign will different depending on the UTC => GPST or GPST => UTC operation order.
I'm pretty sure if you take GSPT <=> GST operations, you will get the correct results

**Comment by ChristopherRabotin** [comment]
Ah, interesting.

So then we can solve this by changing the reference weekday: for the GNSS,
keep the previous Sunday as the start of the week (because that's formally
defined). But for the other ones, we would use the week day of the ref
epoch.

What do you think?
