### ISSUE TITLE
Add Unix as a TimeSystem

### ISSUE THREAD

**Issue by ChristopherRabotin** [nyx-space/hifitime#22]

**Comment by ChristopherRabotin** [comment]
Canceled because it won't add enough value (right now at least) for what I need this module for.

**Comment by mkolopanis** [comment]
I've been finding a lot of use for this crate in some astronomy work and initializing from unix could be really useful. I'm happy make a PR for this if you're still interested in the functionality.

**Comment by ChristopherRabotin** [comment]
Great to hear! Yes, that would be very useful! I'd be happy to review your work, I'm currently quite a bit busy on another project that uses hifitime that's why I haven't reopened this issue recently although I now see the value again.

**Comment by mkolopanis** [comment]
Great! I am also a bit busy but will put it on my list.

**Comment by mkolopanis** [comment]
Adding UNIX as a full TimeSystem brought up a question about gregorian strings.

Since UNIX timestamps are usually just listed in gregorian dates as UTC, would you prefer to automatically output to UTC in `as_gregorian_str` or to error?

**Comment by mkolopanis** [comment]
panicing would be an API change though since `as_gregoriand_str` is infallible currently

**Comment by ChristopherRabotin** [comment]
In which cases can a unix timestamp not be converted to a valid gregorian date? Do you have some code I could look at? I'm not that familiar with UNIX timestamps to UTC conversions, so in my mind it should work out of the box.

**Comment by mkolopanis** [comment]
I think my question more stems from the fact I view UNIX as a time format like GPS seconds which aren't implemented as a full TimeSystem.
It can definitely be converted to a valid gregorian date, but UNIX isn't really a time scale like UTC from my understanding instead it's duration from a different epoch relative to UTC.

Originally I was only thinking about making function to convert to and from Durations since the unix epoch, but the use of TimeSystem gave me pause. 
 
it's pretty easy to define a function like which gives the number of seconds for an Epoch since the UNIX epoch (01 JAN 1970 00:00:00 UTC)
```
    ///Returns the Duration since the UNIX epoch UTC midnight 01 Jan 1970.
    pub fn as_unix_duration(self) -> Duration {
        let cnt = self.get_num_leap_seconds();
        // TAI = UNIX + leap_seconds + UNIX_OFFSET_UTC_SECONDS <=> UNIX = TAI - leap_seconds - UNIX_OFFSET_UTC_SECONDS
        self.0 + i64::from(-cnt) * Unit::Second - UNIX_OFFSET_UTC_SECONDS * Unit::Second
    }
 ```
 
 but the gregorian representation would just be the iso 8601 in whichever time scale you prefer.

Maybe it'll be easier to compare if I open the PR and it can be seen side by side but you are welcome to look at what I've added so far in my fork too.
https://github.com/mkolopanis/hifitime/blob/5972911a7ef9808a0f39f79d4eadd30cc55d74a8/src/epoch.rs

**Comment by ChristopherRabotin** [comment]
I see, thanks for the explanation.

I think you are right that UNIX isn't a time scale / time system like TT since UNIX is just a seconds representation of the UTC time.

In the code you linked to, everything looks fine: where do you envision a function panicking?

**Comment by mkolopanis** [comment]
I think there shouldn't be any new panics introduced actually at this point if we both agree about it as a full TimeSystem. I'll open the PR and you can have a full look.
