### ISSUE TITLE
[Documentation] Comparison with time and chrono crates?

### ISSUE THREAD

**Issue by saona-raimundo** [nyx-space/hifitime#221]
Hi! Thanks for the crate!

Would you consider adding a comparison with the popular `time` and `chrono` crates?

**Comment by ChristopherRabotin** [comment]
That's a good idea. My experience with chrono and time are limited because I have not had the use for them for years, relying only on hifitime.

Off the cuff, I would say that hifitime is more feature complete and more correct: like chrono and time, it can parse date times with and without time zones, but hifitime also handle time systems (thereby supporting specific cases of time dilation). Hifitime also has the concept of `Duration` exposed to users, allowing for stuff like `Epoch::now() + Unit.Hours * 2.3`, as well as [rounding to the nearest unit]https://docs.rs/hifitime/latest/hifitime/prelude/struct.Epoch.html#method.round) , or [floor](https://docs.rs/hifitime/latest/hifitime/prelude/struct.Epoch.html#method.floor) and [ceil](https://docs.rs/hifitime/latest/hifitime/prelude/struct.Epoch.html#method.ceil). 
Hifitime also provides time based iterations with [TimeSeries](https://docs.rs/hifitime/latest/hifitime/struct.TimeSeries.html#method.exclusive): that's very convenient when building interpolations or just ensuring that you're computing some function at a set interval without fears of `f64` rounding your data.

The main possible limitation I have in mind is that I think chrono has a way to format epoch so they can be understood by database natively: I don't suspect that to be too difficult, but I haven't looked into it. The chrono-tz crate also allows _parsing_ with named time zones (but not serializing with those named time zones): hifitime cannot do that.

Somewhat of another limitation is that chrono and time (I think) support time-only stuff: you can't do that with hifitime, you must specify a year, month, and day. But you can set an Epoch's time using [`with_hms`](https://docs.rs/hifitime/latest/hifitime/prelude/struct.Epoch.html#method.with_hms) and [with_hms_strict](https://docs.rs/hifitime/latest/hifitime/prelude/struct.Epoch.html#method.with_hms_strict), or copy it from another Epoch [`with_hms_from`](https://docs.rs/hifitime/latest/hifitime/prelude/struct.Epoch.html#method.with_hms_from).

Overall then, hifitime is more precise, has more features that most users need, and can be used for scientific applications.

**Comment by saona-raimundo** [comment]
Yeah, I think there are very good things in hifitime!

Just looking at the documentation of `time`, there are features to take some random times.
Also, there is [quickcheck](https://crates.io/crates/quickcheck)-based testing.
