### ISSUE TITLE
Support both %yy and %YYYY format ?

### ISSUE THREAD

**Issue by gwbres** [nyx-space/hifitime#267]
https://github.com/nyx-space/hifitime/blob/f0f7fd0fbb1f65d43592f656f97e6d6f1c4048e7/src/efmt/format.rs#L37

Would it be possible to introduce a %y format to describe year on two digits, which you sometimes encounter ?
in which case we would consider Y=0 = 2000. I presume that's what python datetime does

**Comment by ChristopherRabotin** [comment]
Yes, we should have this. It's part of the C89 standard as well. I think it
should be uppercase and lowercase Y.

**Comment by ChristopherRabotin** [comment]
With pleasure! I think that "all" that needs to be done is to add a parsing
token called YearShort (in the format module), and implement the parsing
and formatting. Just by adding that enum variant, that should cause a few
compilation errors, and those are where you'll need to implement the
parsing or formatting of the "short year." I'd prefer not changing the
other enum variant because that would be a breaking change for version 3.

And soon I'll need to pick up the work on version 4. I think your PR was
very close a few months ago, but I got confused about only one test...

**Comment by gwbres** [comment]
I just opened a PR with a first test that does work

**Comment by ChristopherRabotin** [comment]
Implemented in #268, thanks Guillaume !
