### ISSUE TITLE
Roundtrip to/from gpst_nanoseconds are not equal.

### ISSUE THREAD

**Issue by matte1** [nyx-space/hifitime#317]
# Bug report
Roundtrip conversion of an epoch does not result in identical values.

## To Reproduce
```
        let epoch = &Epoch::from_str("2020-11-15 12:34:56.789 TDB").unwrap();
        let epoch_as_nanoseconds = epoch.to_gpst_nanoseconds().unwrap();
        let epoch_from_nanoseconds = Epoch::from_gpst_nanoseconds(epoch_as_nanoseconds);
        assert!(
            epoch == &epoch_from_nanoseconds,
            "{} {}",
            epoch,
            epoch_from_nanoseconds
        );
```

Results in: `2020-11-15T12:34:56.789000000 TDB 2020-11-15T12:34:05.606254592 GPST`

## Expected behavior
A roundtrip using the provided functions should result in identical inputs.

## Version
We noticed this happening on switching from Anise 0.4.0 from 0.3.2

**Comment by gwbres** [comment]
@ChristopherRabotin 

I thought all reciprocal cases were tested, is it not entirely ?

**Comment by ChristopherRabotin** [comment]
I am just as surprised as you are. I have had time to look into this since it was reported a few hours ago, just that I could reproduce that bug when running through the same steps via the FromStr trait. I found a 65 nanosecond difference in the use case I tested.

**Comment by ChristopherRabotin** [comment]
Thanks for the report, Matt. I've found that the crux of the issue is that related to #294 , because the GPST epoch does not seem to be referenced back to the GPS reference epoch when initialized from the string. Instead, for some reason, the 2020 GPST reference is returned as being 4 centuries old: the round trip works fine and as expected for GPSTs less than one century old, or when initialized from the integer of these nanoseconds. This leads to another design related question which I'll address in a discussion.

I'll work to fix this promptly, but further discussions may lead to a breaking change just in time for `4.0.0-alpha`.
